DROP TABLE SHELTER_TABLE;
DROP TABLE DOG_TABLE;
DROP TABLE USR_TABLE;
DROP TABLE VOLUNTEER_TABLE;

-----------------------------------------

DROP SEQUENCE SHELTER_TABLE_SEQ;
DROP SEQUENCE DOG_TABLE_SEQ;
DROP SEQUENCE USR_TABLE_SEQ;
DROP SEQUENCE VOLUNTEER_TABLE_SEQ;

-----------------------------------------

CREATE TABLE SHELTER_TABLE
(
    SHELTERNUM NUMBER PRIMARY KEY,
    SHELTERNAME VARCHAR2(100) NOT NULL,
    SHELTERADDRESS VARCHAR2(100) NOT NULL,
    SHELTERDETAILADDRESS VARCHAR2(100),
    SHELTERADMIN VARCHAR2(100) NOT NULL,
    SHELTERACCOUNT VARCHAR2(100) NOT NULL
);

CREATE TABLE DOG_TABLE
(
   DOGNUM NUMBER PRIMARY KEY,
   DOGAGE NUMBER,
   DOGNAME VARCHAR2(10) NOT NULL,
   DOGBREED VARCHAR2(20),
   DOGGENDER VARCHAR2(2) NOT NULL CHECK (DOGGENDER IN('F','M')),
   DOGDISEASE VARCHAR2(20),
   DOGENTERDATE DATE DEFAULT SYSDATE,
   DOGSPONSOR VARCHAR2(50) DEFAULT '없음',
   SHELTERNUM NUMBER REFERENCES SHELTER_TABLE(SHELTERNUM)
);

CREATE TABLE USR_TABLE
(
    SHELTERNUM NUMBER REFERENCES SHELTER_TABLE(SHELTERNUM), 
    DOGNUM NUMBER REFERENCES DOG_TABLE(DOGNUM),    
    -- 유저 개인 정보
   USRID VARCHAR2(20) PRIMARY KEY NOT NULL,
   USRNAME VARCHAR2(20) NOT NULL,
   USRGENDER VARCHAR2(2) CHECK (USRGENDER IN('F','M')),
   USRAGE NUMBER NOT NULL,
   USRADDRESS VARCHAR2(200) NOT NULL,
   USRPHONE VARCHAR2(20) NOT NULL,
    
    -- 보호자 개인 정보
    PARENTSNAME VARCHAR2(20) default NULL,
    PARENTSAGE NUMBER default NULL,
    PARENTSADDRESS VARCHAR2(200) default NULL,
    PARENTSPHONE VARCHAR2(20) default NULL
);

CREATE TABLE VOLUNTEER_TABLE
(
    VOLUNTEERNUM NUMBER PRIMARY KEY,
    SHELTERNUM NUMBER REFERENCES SHELTER_TABLE(SHELTERNUM),
    USRID VARCHAR2(20) REFERENCES USR_TABLE(USRID) ON DELETE CASCADE,
    
    -- 보호소 및 특정 유기견에게 후원한 금액 정보
    SHELTERDONATION NUMBER,
    DOGDONATION NUMBER,
    
    -- 후원 물품 정보
    PAD NUMBER,
    FOOD NUMBER,
    TISSUE NUMBER,
    
    -- 후원 및 봉사 일시를 받아 올 SYSDATE
    VOLUNTEERDATE DATE DEFAULT SYSDATE,
    
    LUCKYDOG VARCHAR2(10) 
);

-----------------------------------------
        
CREATE SEQUENCE SHELTER_TABLE_SEQ;
CREATE SEQUENCE DOG_TABLE_SEQ;
CREATE SEQUENCE USR_TABLE_SEQ;
CREATE SEQUENCE VOLUNTEER_TABLE_SEQ;

-----------------------------------------
SELECT * FROM DOG_TABLE;
SELECT * FROM USR_TABLE;
SELECT * FROM SHELTER_TABLE;
-----------------------------------------
INSERT INTO SHELTER_TABLE VALUES (SHELTER_TABLE_SEQ.nextval, '유기동물 사랑나누기', '인천광역시 남동구', '인천광역시 남동구 운연동 51번지 2층', '김은비', '660401-01-652748');
INSERT INTO SHELTER_TABLE VALUES (SHELTER_TABLE_SEQ.nextval, '아지네 마을', '경기도 김포시', '비공개입니다.', '이순희', '695037-01-008090');
INSERT INTO SHELTER_TABLE VALUES (SHELTER_TABLE_SEQ.nextval, '비글 구조 네트워크', '서울특별시 용산구', '서울특별시 용산구 용산동 5가 24-1', '유영재', '355-0056-3278-23');
INSERT INTO SHELTER_TABLE VALUES (SHELTER_TABLE_SEQ.nextval, '내사랑 바둑이', '경기도 김포시', '경기도 김포시 양촌읍 누산리 1068-9', '정경순', '140-013-176391');
INSERT INTO SHELTER_TABLE VALUES (SHELTER_TABLE_SEQ.nextval, '행동하는 동물사랑', '경기도 파주시', '경기도 파주시 금촌동 329-355', '이지혜', '469901-04-199087');

INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '2', '오월이', '흑구', 'F', '없음', '2022/04/05', '없음', 1);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '2', '사월이', '황구', 'F', '없음', '2022/04/05', '없음', 1);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '4', '호수', '진도믹스', 'M', '없음', '2022/01/04', '없음', 1);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '7', '에디', '비글', 'M', '귓병', '2021/11/13', '없음', 1);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '6', '몽이', '골든리트리버', 'F', '귓병', '2021/10/15', '없음', 1);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '7', '웅자', '볼테리어', 'F', '피부 알레르기', '2021/08/05', '없음', 1);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '7', '달래', '진도믹스', 'F', '없음', '2021/07/09', '없음', 1);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '1', '고구마', '진도믹스', 'M', '없음', '2022/01/30', '없음', 1);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '1', '메리', '스피츠', 'M', '없음', '2022/02/24', '없음', 1);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '8', '럭키', '골든리트리버', 'F', '없음', '2021/07/07', '없음', 1);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '4', '도담이', '진도믹스', 'F', '없음', '2022/01/05', '없음', 1);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '3', '금자', '황구', 'F', '없음', '2021/10/08', '없음', 1);

INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '3', '새벽이', '흑구', 'M', '없음', '2021/09/05', '없음', 2);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '4', '동행이', '허스키', 'M', '피부 알레르기', '2021/10/08', '없음', 2);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '2', '구름이', '진도믹스', 'M', '없음', '2021/11/24', '없음', 2);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '2', '아롱이', '흑구', 'F', '없음', '2021/12/30', '없음', 2);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '2', '다롱이', '흑구', 'M', '없음', '2022/02/24', '없음', 2);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '13', '삐삐', '시추', 'F', '없음', '2021/09/03', '없음', 2);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '9', '둥이', '시추', 'F', '없음', '2022/03/02', '없음', 2);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '10', '제임스', '미니핀', 'M','없음', '2021/08/29', '없음',2);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5', '옥돌이', '치와와', 'M', '없음', '2022/08/29', '없음', 2);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '6', '상구', '닥스훈트', 'F', '알레르기', '2021/05/27', '없음', 2);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '9', '비누', '비글', 'F', '없음', '2022/03/01', '없음', 2);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '3', '코모', '말티즈', 'F', '없음', '2021/11/13', '없음', 2);

INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5',  '코코', '비글', 'F', '없음', '2022/03/09', '없음',3 );
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '3', '보리', '비글', 'F', '없음', '2021/07/11', '없음',3 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '1', '초코', '비글', 'M', '없음', '2021/05/29', '없음' ,3 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5', '똘이', '비글', 'M', '없음', '2021/10/03', '없음' ,3 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '9', '별이', '비글', 'F', '없음', '2021/05/17', '없음' ,3 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '10', '해피', '비글', 'F', '피부병', '2022/02/01', '없음',3 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '4', '두부', '비글', 'F', '홍역', '2021/01/13', '없음' ,3 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '3', '호두', '비글', 'F', '관절염', '2021/10/20', '없음' ,3 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '2', '마리', '비글', 'F', '없음', '2021/12/29', '없음' ,3 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5', '짱아', '비글', 'M', '없음', '2022/03/08', '없음' ,3 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL,'10', '쿠키', '비글', 'M', '없음', '2021/01/12', '없음' ,3 );
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5',  '콜라', '비글', 'F', '없음', '2022/03/09', '없음',3 );

INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5',  '소라', '비글', 'F', '없음', '2022/03/09', '없음',4 );
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '9', '생강이', '말티즈', 'F', '귓병', '2021/09/17', '없음', 4);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5',  '모카', '비글', 'M', '없음', '2022/03/09', '없음',4 );
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5',  '마루', '비글', 'F', '없음', '2022/03/09', '없음',4 );
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '6', '서원이', '장모치와와', 'F', '없음', '2021/12/23', '없음', 4);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5', '베키', '코카스페니얼', 'M', '없음', '2022/02/10', '없음', 4);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '10', '로사', '말티즈', 'M', '없음', '2021/10/09', '없음', 4);
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5',  '하나', '비글', 'M', '없음', '2022/03/09', '없음',4 );
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5',  '꽃님이', '비글', 'F', '피부병', '2022/03/09', '없음',4 );
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5',  '루나', '비글', 'F', '홍역', '2022/03/09', '없음',4 );
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5',  '사랑', '황구', 'F', '없음', '2022/03/09', '없음',4 );
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '3', '여름', '흑구', 'F', '없음', '2021/07/11', '없음',4 );


INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5',  '찰리', '비글', 'F', '없음', '2022/03/09', '없음',5 );
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5',  '푸푸', '비글', 'F', '없음', '2022/03/09', '없음',5 );
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '1', '미미', '진도믹스', 'M', '없음', '2021/05/29', '없음' ,5 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5', '초롱', '푸들', 'M', '없음', '2021/10/03', '없음' ,5 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '9', '아리', '푸들', 'F', '없음', '2021/05/17', '없음' ,5 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '10', '까미', '말티즈', 'F', '피부병', '2022/02/01', '없음',5 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '4', '낙엽', '요크셔테리어', 'F', '홍역', '2021/01/13', '없음' ,5 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '3', '망고', '요크셔테리어', 'F', '관절염', '2021/10/20', '없음' ,5 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '2', '미니', '푸들', 'F', '없음', '2021/12/29', '없음' ,5 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL, '5', '고니', '푸들', 'M', '없음', '2022/03/08', '없음' ,5 ); 
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL,'10', '모찌', '비숑프리제', 'M', '없음', '2021/01/12', '없음' ,5 );
INSERT INTO DOG_TABLE VALUES (DOG_TABLE_SEQ.NEXTVAL,'10', '뭉치', '말티즈', 'M', '없음', '2021/01/12', '없음' ,5 );